service: convio-chatbot

	
package:
  patterns:
    - index.js

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, "ap-south-1"}
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  memorySize: 512
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

# The `functions` block defines what code to deploy
functions:
  API:
    handler: index.handler
    # The `events` block defines how to trigger the uploadImage.handler code
    events:
      - http:
          path: healthcheck
          method: post
          cors: true
          request:
            template:
              application/json: '$input.json("$")'
      - http:
          path: detectIndent
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Accept
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            template:
              application/json: '$input.json("$")'
  webhook:
    handler: index.webhook
    # The `events` block defines how to trigger the uploadImage.handler code
    events:
      - http:
          path: webhook
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Accept
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            template:
              application/json: '$input.json("$")'



